version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vulnerability-management
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: vulnerability-management
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: your-smtp-user
      SMTP_PASS: your-smtp-pass
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
